Feature/in class validation
csOdin/Validator pull request #3
Opened 2020-10-06 20:43 UTC by cgxarrie

2020-10-07 06:20 UTC, VoldarGames approved these changes

2020-10-07 06:20 UTC, VoldarGames commented on README.md
> +```
puedes añadir ```csharp  al markdown para q se vea más bonito :)

2020-10-07 06:20 UTC, VoldarGames commented on csOdin.Validator.Tests/BreakOnFailureTests.cs
> +            _validationStepSuccess1 = ValidationStep<string>.Create(s1);
molarian mejores nombres, incluso para un test, q no s1,f2..

2020-10-07 06:20 UTC, VoldarGames commented on csOdin.Validator.Tests/DummyValidator.cs
> +        protected override void Setup(T command)
un override vacio??

2020-10-07 06:20 UTC, VoldarGames commented on csOdin.Validator/ValidationResult_T.cs
> +﻿namespace csOdin.Validator
El nombre de este archivo es feote :D

2020-10-07 06:20 UTC, VoldarGames commented on csOdin.Validator.Tests/InClassValidation/DummyClassWithValidator.cs
> +            var result = validator.Validate(command);
await aqui y te evitas el .Result de abajo

2020-10-07 06:22 UTC, VoldarGames requested changes
.

2020-10-07 07:38 UTC, cgxarrie commented on README.md
> +            var validator = new Validator<Myommand>();
fixed en siguiente push

2020-10-07 07:38 UTC, cgxarrie commented on README.md
> +```
fixed en siguiente push

2020-10-07 07:38 UTC, cgxarrie commented on csOdin.Validator.Tests/BreakOnFailureTests.cs
> +            _validationStepSuccess1 = ValidationStep<string>.Create(s1);
fixed en siguiente push

2020-10-07 07:41 UTC, cgxarrie commented on csOdin.Validator/ValidationResult_T.cs
> +﻿namespace csOdin.Validator
Movido al archivo ValidationResult.cs

2020-10-07 11:33 UTC, cgxarrie commented on csOdin.Validator.Tests/DummyValidator.cs
> +        protected override void Setup(T command)
Es sólo en el test, en un dummy validator.
Estoy obligado a implementarlo porque es abstract

2020-10-08 12:12 UTC, VoldarGames approved these changes

2020-10-08 12:12 UTC, merged